export const SUPABASE_PROJECT_URL = 'https://bvjijljmrkpqxsruaudq.supabase.co'
export const SUPABASE_API_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2amlqbGptcmtwcXhzcnVhdWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzQzMTE4NzQsImV4cCI6MTk4OTg4Nzg3NH0.fiKPDAwlX8_O5a84694KpdzlsxqnCVv7lHx1fSrYZYM'
